# Site settings
title: cat tonivade > /dev/blog
email: me@tonivade.es
description: > # this means to ignore newlines until "baseurl:"
  Personal Weblog, about software development, technology and more
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.tonivade.es" # the base hostname & protocol for your site
github_username:  tonivade
mastodon_username: tonivade

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
